# Generated by Django 5.1.6 on 2025-03-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedzip',
            old_name='file',
            new_name='zip_file',
        ),
        migrations.RemoveField(
            model_name='uploadedzip',
            name='name',
        ),
        migrations.AddField(
            model_name='uploadedexcel',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedzip',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedzip',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
