# Generated by Django 5.1.6 on 2025-03-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_api', '0002_rename_file_uploadedzip_zip_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='uploadedexcel',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
