# Generated by Django 5.1.6 on 2025-03-10 07:28

import aap_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_api', '0003_alter_exceldata_is_visible_alter_uploadedexcel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceldata',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedexcel',
            name='file',
            field=models.FileField(help_text='Upload Excel file (.xlsx, .xls)', upload_to='excel_uploads/', validators=[aap_api.models.validate_excel_file]),
        ),
    ]
