# Generated by Django 5.1.6 on 2025-03-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_api', '0004_remove_exceldata_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload ZIP file containing Excel files (.xlsx, .xls)', upload_to='zip_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('total_records', models.IntegerField(default=0)),
            ],
        ),
    ]
