# Generated by Django 5.1.6 on 2025-03-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_api', '0005_zipupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipupload',
            old_name='total_records',
            new_name='records_imported',
        ),
        migrations.AlterField(
            model_name='zipupload',
            name='file',
            field=models.FileField(upload_to='zip_uploads/'),
        ),
    ]
